version: "3.8"
services:
  mks-postgres:
    image: postgres:15.3-alpine
    container_name: mks-postgres
    restart: always
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - mks-bridge
  mks-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mks-pgadmin
    restart: always
    depends_on:
      - mks-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8080:80
    networks:
      - mks-bridge

  redis:
      image: redis
      container_name: redis-mks 
      networks:
        - mks-bridge
      ports:
        - "6379:6379"
  mks:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: mks-app
      restart: unless-stopped
      ports:
        - "3000:3000"
      environment:
        DB_HOST: mks-postgres
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        REDIS_HOST: redis
        REDIS_PORT: 6379
      depends_on:
        - mks-postgres
        - redis
      volumes:
        - ./src:/app/src
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3" 
      networks:
        - mks-bridge

networks:
  mks-bridge:
    driver: bridge

volumes:
  postgres-data: